invitation_send:
    path: invitations
    controller: App\Controller\API\V1\InvitationController::sendInvitation
    methods: [POST]

invitation_accept:
    path: invitations/{id}/accept
    controller: App\Controller\API\V1\InvitationController::acceptInvitation
    methods: [PATCH]
    requirements:
        id: '\d+'

invitation_decline:
    path: invitations/{id}/decline
    controller: App\Controller\API\V1\InvitationController::declineInvitation
    methods: [PATCH]
    requirements:
        id: '\d+'

invitation_cancel:
    path: invitations/{id}/cancel
    controller: App\Controller\API\V1\InvitationController::cancelInvitation
    methods: [PATCH]
    requirements:
        id: '\d+'
